version: '3.9'

services:
  app:
    container_name: app
    image: 'example_app_img:1.0'
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgresdb
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresdb:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres